export {default as Home } from './Home.jsx'
export {default as About} from './About.jsx'
export {default as Products} from './Products.jsx'
export {default as Contact} from './Contact.jsx'
export {default as Admin} from './Admin.jsx'